version: '3'
services:
  elasticsearch:
    image: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - /data:/usr/share/elasticsearch/data
    networks:
      - default
  kibana:
    image: kibana
    ports:
     - "5601:5601"
    links:
     - elasticsearch
    networks:
      - default
  logstash:
    build: logstash
    command: logstash -f /conf/logstash-spring-boot.conf
    ports:
     - "5043:5043"
     - "5044:5044"
    links:
     - elasticsearch
    networks:
      - default
  mysql:
    image: mysql:5.6.23
    container_name: mysql
    env_file:
     - env
    networks:
      - default
  salesorderapi:
    image: azpent/salesorderapi
    depends_on:
     - serverdiscovery
    links:
     - mysql
     - logstash
    networks:
      - default
  serverconfig:
    image: azpent/serverconfig
    ports:
     - "3333:3333"
    container_name: serverconfig
    networks:
      - default
  serverdiscovery:
    image: azpent/serverdiscovery
    ports:
     - "8761:8761"
    container_name: serverdiscovery
    depends_on:
     - serverconfig
    networks:
      - default
  serverzuul:
    image: azpent/serverzuul
    ports:
     - "8097:8097"
    container_name: serverzuul
    depends_on:
     - serverconfig
    networks:
      - default
  serverturbine:
    image: azpent/serverturbine
    ports:
     - "8081:8081"
    container_name: serverturbine
    depends_on:
     - serverdiscovery
    links:
     - salesorderapi
    networks:
      - default
  serverhystrixdashboard:
    image: azpent/serverhystrixdashboard
    ports:
     - "8089:8089"
    container_name: serverhystrixdashboard
    depends_on:
     - serverdiscovery
    networks:
      - default
networks:
  default:
    external:
      name: demomicro

